# Generated by Django 5.2.10 on 2026-01-10 23:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('LOST', 'Lost'), ('DO_NOT_PURSUE', 'Do Not Pursue')], db_index=True, max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', max_length=160)),
                ('primary_phone', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('primary_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('medium', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('campaign', models.CharField(blank=True, default='', max_length=120)),
                ('content', models.CharField(blank=True, default='', max_length=120)),
                ('term', models.CharField(blank=True, default='', max_length=120)),
                ('utm', models.JSONField(blank=True, null=True)),
                ('marketing_opt_in', models.BooleanField(db_index=True, default=True)),
                ('do_not_contact', models.BooleanField(db_index=True, default=False)),
                ('locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(db_index=True, default='NEW', max_length=40)),
                ('score_bucket', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('qualification', models.JSONField(blank=True, null=True)),
                ('first_response_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_contact_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('external_refs', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('canceled', 'Canceled')], db_index=True, default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadTimelineEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('meeting', 'Meeting'), ('system', 'System')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadIdentityPoint',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('national_id', 'National ID'), ('other', 'Other')], db_index=True, max_length=20)),
                ('value', models.CharField(db_index=True, max_length=160)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_points', to='leads.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'value'], name='leads_leadi_type_fbf4d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'value'), name='uniq_identity_type_value')],
            },
        ),
    ]
