# Generated by Django 5.2.10 on 2026-01-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadidentitypoint',
            name='uniq_identity_type_value',
        ),
    ]
