# Generated by Django 5.2.10 on 2026-01-12 20:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_leadidentitypoint_uniq_identity_type_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('distribution_method', models.CharField(choices=[('ROUND_ROBIN', 'Round Robin'), ('WEIGHTED', 'Weighted Random'), ('BROADCAST', 'Broadcast / Cherry Pick')], default='ROUND_ROBIN', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project_scope', models.CharField(blank=True, help_text='Matches Lead.interest', max_length=120, null=True)),
                ('language', models.CharField(blank=True, help_text="e.g. 'en', 'ar'", max_length=10, null=True)),
                ('source', models.CharField(blank=True, help_text="e.g. 'whatsapp', 'walk_in'", max_length=80, null=True)),
                ('score_bucket', models.CharField(blank=True, help_text="e.g. 'HOT', 'VIP'", max_length=20, null=True)),
                ('sla_minutes', models.PositiveIntegerField(default=60, help_text='Expected response time in minutes for leads matching this rule.')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.salesteam')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leads.salesteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_assigned_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
