# Generated by Django 5.2.10 on 2026-01-13 11:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_salesteam_routingrule_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBucket',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_score', models.IntegerField(help_text='Minimum score required', unique=True)),
                ('priority', models.IntegerField(default=0, help_text='High priority buckets checked first')),
                ('color', models.CharField(default='#FFFFFF', help_text='Hex code for UI', max_length=20)),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal name for this rule', max_length=255)),
                ('category', models.CharField(choices=[('budget', 'Budget'), ('title', 'Job Title'), ('source', 'Source'), ('country', 'Country')], db_index=True, max_length=50)),
                ('keyword', models.CharField(help_text="Value to match (e.g., 'CEO', '10M+')", max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains')], default='contains', max_length=20)),
                ('points', models.IntegerField(default=0, help_text='Points to add (can be negative)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
