# Generated by Django 5.2.10 on 2026-01-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_calllog_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.ForeignKey(blank=True, help_text='The specific reason code if stage is LOST or DO_NOT_PURSUE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_leads', to='leads.reasoncode'),
        ),
    ]
