# Generated by Django 5.2.10 on 2026-01-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_lost_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringrule',
            name='category',
            field=models.CharField(choices=[('budget', 'Budget'), ('title', 'Job Title'), ('source', 'Source'), ('country', 'Country'), ('activity', 'Activity / Behavior')], db_index=True, max_length=50),
        ),
    ]
