# Generated by Django 5.2.10 on 2026-01-10 23:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(db_index=True, default='api', max_length=32)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('entity_type', models.CharField(db_index=True, max_length=80)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='audit_audit_entity__73f5bf_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_58da28_idx'), models.Index(fields=['request_id'], name='audit_audit_request_c59dc1_idx')],
            },
        ),
    ]
